### ISSUE TITLE
New requirement: Add support to ACL

### ISSUE THREAD

**Issue by robot-dot-win** [NOBLES5E/cproxy#129]
cproxy is really so nice!

Sometimes users need to redirect only specific dest ports and/or dest hosts(IP or domain name), like this scenario:
[Only redirect a specific dest port](https://github.com/rofl0r/proxychains-ng/issues/571#issuecomment-2236445970)

So would you please consider supporting ACL in the future :)

**Comment by NOBLES5E** [comment]
Thanks for your suggestion.

As you probably noticed, cproxy is a very simple program with less than 1k LOC. An ACL system alone will cost more than that. We prefer to keep cproxy simple at the moment.
