### ISSUE TITLE
[Bug] Cannot proxy processes in systemd-nspawn container

### ISSUE THREAD

**Issue by arenekosreal** [NOBLES5E/cproxy#134]
I am using cproxy with archlinux's [devtools](https://archlinux.org/packages/extra/any/devtools/) to do some packaging work. But I find that cproxy does not work with processes in systemd-nspawn container launched by packaging script. For example, devtools has a command named `makechrootpkg`, which will start a systemd-nspawn container to build software and create package for archlinux. But processes in container are not proxied correctly because systemd-nspawn will start a new cgroup slice, which results that processes in container does not belongs to slice created by cproxy.

Here are images about `systemd-cgls` output:
![image](https://github.com/user-attachments/assets/a93b5a21-46ee-4f75-8570-3539c90fa373)
![image](https://github.com/user-attachments/assets/29f475de-32f3-4b91-ac3e-a7d13d42b29d)

Noticed that there is a slice named `devtools.slice`, which name seems to be static. So I think we may consider adding a new feature to ~~proxy existing slice~~? Nevermind, iptables does this, but I think cproxy can handle those programs correctly.

**Comment by NOBLES5E** [comment]
It would be possible to add a CLI argument to include additional cgroup slices to proxy. However, is there a proper way to detect this automatically?

**Comment by arenekosreal** [comment]
I don't think there is any way to detect the creation of new cgroup automatically. 

According to [this](https://stackoverflow.com/a/35888128) stackoverflow answer, I did not find any way to notify user when cgroup changes for cgroupv1, but cgroupv2 may be better, it has a `cgroup.events` file for non-root cgroups, we can even use tools like `inotify` to check filesystem changes.

There is another tool similar to cproxy named [cgtproxy](https://github.com/black-desk/cgtproxy), it [uses a filesystem monitor](https://github.com/black-desk/cgtproxy/blob/master/pkg/cgfsmon/new.go#L51) to catch the creation event of cgroup, but this is not work with cgroupv1 according to the stackoverflow answer mentioned before.

I think we may scan all cgroups or let user provide target cgroup slice. But scanning all cgroups may be a huge performance problem. I personally prefer the latter way, we can add a cli argument and user should fill it with full paths of target cgroup slices, we simply call iptables to redirect their traffic.

**Comment by NOBLES5E** [comment]
supported in v4.2.2
