### ISSUE TITLE
跟clash的redir-port无法打通

### ISSUE THREAD

**Issue by pc10201** [NOBLES5E/cproxy#21]
跟clash的redir-port无法打通

clash的redir-port和tproxy是等同的吗？

**Comment by NOBLES5E** [comment]
I have not used clash before. Traditionally `redir` corresponds to the `redirect` mode (which means you should use `--mode redirect` instead of `--mode tproxy` with cproxy).

Let me know if that still does not work (with a reproducible example).

**Comment by pc10201** [comment]
It do not work
cproxy --port 7892 --redirect-dns --mode redirect --  curl ip.sb

**Comment by NOBLES5E** [comment]
> It do not work
> cproxy --port 7892 --redirect-dns --mode redirect -- curl ip.sb

Could you share your clash setup? I cannot reproduce with

```
clash -f config.yml
```

```
❯ cproxy --mode redirect --port 7892 curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

where `config.yml` looks like

```
redir-port: 7892
```

**Comment by NOBLES5E** [comment]
closed due to inactivity
