### ISSUE TITLE
[功能需求]是否可以增加选项使用局域网已有的socks5代理服务器？

### ISSUE THREAD

**Issue by egg1234** [NOBLES5E/cproxy#73]
举例局域网内已经有socks5代理 10.0.0.5:1080

是否可以增加选项使用局域网已有的这个socks5代理服务器？

例如使用格式是：
cproxy --ip 10.0.0.5 --port 1080 --redirect-dns -- <your-program>

谢谢！

**Comment by NOBLES5E** [comment]
Thanks for the feature request. This is exactly what [proxychains-ng](https://github.com/rofl0r/proxychains-ng) supports. Personally I'd like to keep cproxy simple without messing with socks proxies.

**Comment by egg1234** [comment]
由于cproxy使用cgroup方法，所以在很多应用场合的适应性是比proxychains-ng要好的，但cproxy现在只能支持本机代理端口，实际上是要求用户必须在本机另外搭一个代理，对于很多应用场景其实用户是不想在本机安装太多的第三方软件的，所以我认为如果可能的话cproxy支持使用局域网的socsk5代理是给用户一个更好的选择，毕竟一款应用的适应场景宽一些，用户群就大一些
